-- MySQL Script generated by MySQL Workbench
-- sex 14 fev 2020 10:09:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aldeia_db_beta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aldeia_db_beta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aldeia_db_beta` DEFAULT CHARACTER SET utf8 ;
USE `aldeia_db_beta` ;

-- -----------------------------------------------------
-- Table `aldeia_db_beta`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aldeia_db_beta`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ativo` INT NOT NULL DEFAULT 1,
  `nivel` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aldeia_db_beta`.`docs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aldeia_db_beta`.`docs` (
  `id_doc` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `envio` DATE NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_doc`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
